{
 "title": "Sample",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": "label_values(mongodb_connections, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Replication state",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of clients currently connected to the database server",
     "type": "graph",
     "description": "connections.current",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_connections{state=\"current\",instance=~\"$env\"}"
      }
     ]
    },
    {
     "title": "Number of unused connections available for new clients",
     "type": "graph",
     "description": "connections.available",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_connections{state=\"available\",instance=~\"$env\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of all documents (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_log_bytes_total"
      }
     ]
    },
    {
     "title": "Maximum cache size configured (bytes)",
     "type": "graph",
     "description": "wiredTiger.cache.maximum bytes configured",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_cache_max_bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory & Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amount of memory used by the database process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_memory{type=\"resident\"}"
      }
     ]
    },
    {
     "title": "Virtual memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_memory{type=\"virtual\"}"
      }
     ]
    },
    {
     "title": "Amount of space taken by cached data (bytes)",
     "type": "graph",
     "description": "wiredTiger.cache.bytes currently in the cache",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_cache_bytes"
      }
     ]
    },
    {
     "title": "Amount of space taken by dirty data in the cache (bytes)",
     "type": "graph",
     "description": "wiredTiger.cache.tracked  dirty bytes in the cache",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_cache_bytes{type=\"dirty\"}"
      }
     ]
    },
    {
     "title": "Number of pages evicted from the cache",
     "type": "graph",
     "description": "wiredTiger.cache.unmodified pages evicted + wiredTiger.cache.modified pages evicted",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_cache_evicted_total"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read requests per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_op_counters_total{type=\"query\"}"
      },
      {
       "expr": "mongodb_mongod_op_counters_total{type=\"getmore\"}"
      }
     ]
    },
    {
     "title": "Write requests per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nmongodb_mongod_op_counters_total{type=\"insert\"}"
      },
      {
       "expr": "mongodb_mongod_op_counters_total{type=\"update\"}"
      },
      {
       "expr": "mongodb_mongod_op_counters_total{type=\"delete\"}"
      }
     ]
    },
    {
     "title": "Number of clients with read operations in progress or queued",
     "type": "graph",
     "description": "read/write operations: globalLock_client",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_global_lock_client{type=\"reader\"}"
      }
     ]
    },
    {
     "title": "Number of clients with write operations in progress or queued",
     "type": "graph",
     "description": "read/write operations: globalLock_client",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_global_lock_client{type=\"writer\"}"
      }
     ]
    },
    {
     "title": "Number of cursors currently opened by MongoDB for clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_metrics_cursor_open{state=\"pinned\"}"
      },
      {
       "expr": "mongodb_mongod_metrics_cursor_open{state=\"total\"}"
      }
     ]
    },
    {
     "title": "Number of cursors that have timed out during the selected time period",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_metrics_cursor_timed_out_total"
      }
     ]
    },
    {
     "title": "The number of open cursors with timeout disabled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_metrics_cursor_open{state=\"noTimeout\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oplog size current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_replset_oplog_size_bytes{type=\"current\",instance=~\"$env\"}/1024/1024"
      }
     ]
    },
    {
     "title": "Oplog size storage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_replset_oplog_size_bytes{type=\"storage\",instance=~\"$env\"}/1024/1024"
      }
     ]
    },
    {
     "title": "Replication lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_replset_member_replication_lag{instance=~\"$env\"}"
      }
     ]
    },
    {
     "title": "Replica set member state",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_replset_member_state{instance=~\"$env\"}"
      }
     ]
    },
    {
     "title": "Number of times MongoDB had to request from disk (per sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_extra_info_page_faults_total"
      }
     ]
    },
    {
     "title": "Number of objects (documents) among all the collections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_metrics_document_total{type=\"\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of read tickets in use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{type=\"read\"}"
      }
     ]
    },
    {
     "title": "Number of write tickets in use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{type=\"write\"}"
      }
     ]
    },
    {
     "title": "Number of available read tickets remaining",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{type=\"read\"}"
      }
     ]
    },
    {
     "title": "Number of available write tickets remaining",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{type=\"write\"}"
      }
     ]
    },
    {
     "title": "Total Check points(Recovery points)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of read requests currently queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_global_lock_current_queue{type=\"reader\",instance=~\"$env\"}"
      }
     ]
    },
    {
     "title": "Number of write requests currently queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_global_lock_current_queue{type=\"writer\",instance=~\"$env\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors: asserts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of message assertions raised",
     "type": "graph",
     "description": "asserts: msg",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_asserts_total{type=\"msg\"}"
      }
     ]
    },
    {
     "title": "Number of warning assertions raised",
     "type": "graph",
     "description": "asserts: warning",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_asserts_total{type=\"warning\"}"
      }
     ]
    },
    {
     "title": "Number of regular assertions raised",
     "type": "graph",
     "description": "asserts: regular",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_asserts_total{type=\"regular\"}"
      }
     ]
    },
    {
     "title": "Number of assertions corresponding to errors generated by users",
     "type": "graph",
     "description": "asserts: user",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_asserts_total{type=\"user\"}"
      }
     ]
    },
    {
     "title": "Assertion rollover",
     "type": "graph",
     "description": "asserts: rollovers (The MongoDB log files will give you more details as assertions counters will rollover to zero if the MongoDB’s process is restarted or after 2^30 assertions)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_asserts_total{type=\"rollovers\"}"
      }
     ]
    }
   ]
  }
 ]
}